### PR TITLE
Add "Run on Replit" badge

### PR DESCRIPTION
**Pull request by hackermondev**
Glitch is already there, but Replit is another important business in the same market. And some individuals may prefer Replit because of the additional resources it provides, as well as the ease with which it can be set up and a thousand other features I could list. @shaydewael

### CODE REVIEW

**Comment by hackermondev** [comment]
I don't know where you got your information but they in fact **CAN** run v13 discord bots, I run a few bots on there. A few months ago, they couldn't because the wrong node version was installed but they've updated the node version on their servers.

**Comment by shaydewael** [comment]
@hackermondev I'm not against having Replit as another option (I was originally using it when writing the guide because of its TypeScript support), but I'll need to test it and add instructions about getting the interactions endpoint URL. Stay tuned!

**Comment by KK-Designs** [comment]
> @KK-Designs I don't know where you got your information but they in fact **CAN** run v13 discord bots, I run a few bots on there. A few months ago, they couldn't because the wrong node version was installed but they've updated the node version on their servers.

They can?? I didn't know that lol

**Comment by shaydewael** [comment]
Sorry this took longer than anticipated 😓 

But I updated this project (I needed to do a couple of other updates and custom configs, and wanted to change some Replit-specific project stuff, so ended up making [a different PR](https://github.com/discord/discord-example-app/pull/3/files)) and the [Getting Started guide](https://github.com/discord/discord-api-docs/pull/4890)

**Pull request closed without merging**
